# Loading the Dataset

## 1. Download and load the dataset.

In [15]:
import pandas as pd

In [16]:
url = "https://raw.githubusercontent.com/tidyverse/dplyr/main/data-raw/starwars.csv"

In [17]:
starwars = pd.read_csv(url)
starwars.head()

,name,height,mass,hair_color,skin_color,eye_color,birth_year,sex,gender,homeworld,species,films,vehicles,starships
0,Luke Skywalker,172.0,77.0,blond,fair,blue,19.0,male,masculine,Tatooine,Human,"A New Hope, The Empire Strikes Back, Return of...","Snowspeeder, Imperial Speeder Bike","X-wing, Imperial shuttle"
1,C-3PO,167.0,75.0,NaN,gold,yellow,112.0,none,masculine,Tatooine,Droid,"A New Hope, The Empire Strikes Back, Return of...",NaN,NaN
2,R2-D2,96.0,32.0,NaN,"white, blue",red,33.0,none,masculine,Naboo,Droid,"A New Hope, The Empire Strikes Back, Return of...",NaN,NaN
3,Darth Vader,202.0,136.0,none,white,yellow,41.9,male,masculine,Tatooine,Human,"A New Hope, The Empire Strikes Back, Return of...",NaN,TIE Advanced x1
4,Leia Organa,150.0,49.0,brown,light,brown,19.0,female,feminine,Alderaan,Human,"A New Hope, The Empire Strikes Back, Return of...",Imperial Speeder Bike,NaN

In [18]:
starwars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        87 non-null     object
 1   height      81 non-null     float64
 2   mass        59 non-null     float64
 3   hair_color  82 non-null     object
 4   skin_color  87 non-null     object
 5   eye_color   87 non-null     object
 6   birth_year  43 non-null     float64
 7   sex         83 non-null     object
 8   gender      83 non-null     object
 9   homeworld   77 non-null     object
 10  species     83 non-null     object
 11  films       87 non-null     object
 12  vehicles    11 non-null     object
 13  starships   20 non-null     object
dtypes: float64(3), object(11)
memory usage: 9.6+ KB

## 2. Inspect the dataset

In [19]:
starwars.head(10)

,name,height,mass,hair_color,skin_color,eye_color,birth_year,sex,gender,homeworld,species,films,vehicles,starships
0,Luke Skywalker,172.0,77.0,blond,fair,blue,19.0,male,masculine,Tatooine,Human,"A New Hope, The Empire Strikes Back, Return of...","Snowspeeder, Imperial Speeder Bike","X-wing, Imperial shuttle"
1,C-3PO,167.0,75.0,NaN,gold,yellow,112.0,none,masculine,Tatooine,Droid,"A New Hope, The Empire Strikes Back, Return of...",NaN,NaN
2,R2-D2,96.0,32.0,NaN,"white, blue",red,33.0,none,masculine,Naboo,Droid,"A New Hope, The Empire Strikes Back, Return of...",NaN,NaN
3,Darth Vader,202.0,136.0,none,white,yellow,41.9,male,masculine,Tatooine,Human,"A New Hope, The Empire Strikes Back, Return of...",NaN,TIE Advanced x1
4,Leia Organa,150.0,49.0,brown,light,brown,19.0,female,feminine,Alderaan,Human,"A New Hope, The Empire Strikes Back, Return of...",Imperial Speeder Bike,NaN
5,Owen Lars,178.0,120.0,"brown, grey",light,blue,52.0,male,masculine,Tatooine,Human,"A New Hope, Attack of the Clones, Revenge of t...",NaN,NaN
6,Beru Whitesun Lars,165.0,75.0,brown,light,blue,47.0,female,feminine,Tatooine,Human,"A New Hope, Attack of the Clones, Revenge of t...",NaN,NaN
7,R5-D4,97.0,32.0,NaN,"white, red",red,NaN,none,masculine,Tatooine,Droid,A New Hope,NaN,NaN
8,Biggs Darklighter,183.0,84.0,black,light,brown,24.0,male,masculine,Tatooine,Human,A New Hope,NaN,X-wing
9,Obi-Wan Kenobi,182.0,77.0,"auburn, white",fair,blue-gray,57.0,male,masculine,Stewjon,Human,"A New Hope, The Empire Strikes Back, Return of...",Tribubble bongo,"Jedi starfighter, Trade Federation cruiser, Na..."

In [20]:
print("\nSummary of the dataset structure:")
print(f"- Number of rows: {starwars.shape[0]}")
print(f"- Number of columns: {starwars.shape[1]}")

print("\nColumn names and their data types:")
print(starwars.dtypes)

print("\nInformation on any missing values:")
print(starwars.isnull().sum())

Summary of the dataset structure:
- Number of rows: 87
- Number of columns: 14

Column names and their data types:
name           object
height        float64
mass          float64
hair_color     object
skin_color     object
eye_color      object
birth_year    float64
sex            object
gender         object
homeworld      object
species        object
films          object
vehicles       object
starships      object
dtype: object

Information on any missing values:
name           0
height         6
mass          28
hair_color     5
skin_color     0
eye_color      0
birth_year    44
sex            4
gender         4
homeworld     10
species        4
films          0
vehicles      76
starships     67
dtype: int64

## 3. Handle missing data

In [21]:
print("Number of missing values in each column:")
print(starwars.isnull().sum())

Number of missing values in each column:
name           0
height         6
mass          28
hair_color     5
skin_color     0
eye_color      0
birth_year    44
sex            4
gender         4
homeworld     10
species        4
films          0
vehicles      76
starships     67
dtype: int64

In [22]:
num_cols = starwars.select_dtypes(include=['float64', 'int64']).columns
cat_cols = starwars.select_dtypes(include=['object']).columns

starwars[num_cols] = starwars[num_cols].fillna(starwars[num_cols].mean())
starwars[cat_cols] = starwars[cat_cols].fillna("Unknown")

print("Numeric columns filled with mean")
print("Categorical columns filled with 'Unknown'")

Numeric columns filled with mean
Categorical columns filled with 'Unknown'

In [23]:
print("\nConfirming missing values after handling:")
print(starwars.isnull().sum())

Confirming missing values after handling:
name          0
height        0
mass          0
hair_color    0
skin_color    0
eye_color     0
birth_year    0
sex           0
gender        0
homeworld     0
species       0
films         0
vehicles      0
starships     0
dtype: int64

## Expected Output

- this dataset contains 87 rows and 14 columns
- height, mass, hair_color, birth_year, sex, gender, homeworld, species, vehicles and starships contain missing value
- Missing numerical values were filled with the mean of their respective columns and missing categorical values were filled with 'Unknown'.
- After handling, there should be no remaining missing values: 0 missing values remaining.

In [24]:
display(starwars.head(10))

,name,height,mass,hair_color,skin_color,eye_color,birth_year,sex,gender,homeworld,species,films,vehicles,starships
0,Luke Skywalker,172.0,77.0,blond,fair,blue,19.000000,male,masculine,Tatooine,Human,"A New Hope, The Empire Strikes Back, Return of...","Snowspeeder, Imperial Speeder Bike","X-wing, Imperial shuttle"
1,C-3PO,167.0,75.0,Unknown,gold,yellow,112.000000,none,masculine,Tatooine,Droid,"A New Hope, The Empire Strikes Back, Return of...",Unknown,Unknown
2,R2-D2,96.0,32.0,Unknown,"white, blue",red,33.000000,none,masculine,Naboo,Droid,"A New Hope, The Empire Strikes Back, Return of...",Unknown,Unknown
3,Darth Vader,202.0,136.0,none,white,yellow,41.900000,male,masculine,Tatooine,Human,"A New Hope, The Empire Strikes Back, Return of...",Unknown,TIE Advanced x1
4,Leia Organa,150.0,49.0,brown,light,brown,19.000000,female,feminine,Alderaan,Human,"A New Hope, The Empire Strikes Back, Return of...",Imperial Speeder Bike,Unknown
5,Owen Lars,178.0,120.0,"brown, grey",light,blue,52.000000,male,masculine,Tatooine,Human,"A New Hope, Attack of the Clones, Revenge of t...",Unknown,Unknown
6,Beru Whitesun Lars,165.0,75.0,brown,light,blue,47.000000,female,feminine,Tatooine,Human,"A New Hope, Attack of the Clones, Revenge of t...",Unknown,Unknown
7,R5-D4,97.0,32.0,Unknown,"white, red",red,87.565116,none,masculine,Tatooine,Droid,A New Hope,Unknown,Unknown
8,Biggs Darklighter,183.0,84.0,black,light,brown,24.000000,male,masculine,Tatooine,Human,A New Hope,Unknown,X-wing
9,Obi-Wan Kenobi,182.0,77.0,"auburn, white",fair,blue-gray,57.000000,male,masculine,Stewjon,Human,"A New Hope, The Empire Strikes Back, Return of...",Tribubble bongo,"Jedi starfighter, Trade Federation cruiser, Na..."

In [25]:
display(starwars.tail(10))

,name,height,mass,hair_color,skin_color,eye_color,birth_year,sex,gender,homeworld,species,films,vehicles,starships
77,Grievous,216.000000,159.000000,none,"brown, white","green, yellow",87.565116,male,masculine,Kalee,Kaleesh,Revenge of the Sith,Tsmeu-6 personal wheel bike,Belbullab-22 starfighter
78,Tarfful,234.000000,136.000000,brown,brown,blue,87.565116,male,masculine,Kashyyyk,Wookiee,Revenge of the Sith,Unknown,Unknown
79,Raymus Antilles,188.000000,79.000000,brown,light,brown,87.565116,male,masculine,Alderaan,Human,"A New Hope, Revenge of the Sith",Unknown,Unknown
80,Sly Moore,178.000000,48.000000,none,pale,white,87.565116,Unknown,Unknown,Umbara,Unknown,"Attack of the Clones, Revenge of the Sith",Unknown,Unknown
81,Tion Medon,206.000000,80.000000,none,grey,black,87.565116,male,masculine,Utapau,Pau'an,Revenge of the Sith,Unknown,Unknown
82,Finn,174.604938,97.311864,black,dark,dark,87.565116,male,masculine,Unknown,Human,The Force Awakens,Unknown,Unknown
83,Rey,174.604938,97.311864,brown,light,hazel,87.565116,female,feminine,Unknown,Human,The Force Awakens,Unknown,Unknown
84,Poe Dameron,174.604938,97.311864,brown,light,brown,87.565116,male,masculine,Unknown,Human,The Force Awakens,Unknown,X-wing
85,BB8,174.604938,97.311864,none,none,black,87.565116,none,masculine,Unknown,Droid,The Force Awakens,Unknown,Unknown
86,Captain Phasma,174.604938,97.311864,none,none,unknown,87.565116,female,feminine,Unknown,Human,The Force Awakens,Unknown,Unknown